"""Copy SQLite state into PostgreSQL before switching a deployment over.

``caveman ops migrate-to-postgres`` moves the two stores the API and workers
share (the kernel's operational store and the platform store) from the SQLite
files under ``CAVEMAN_DATA_DIR`` into the schemas ``CAVEMAN_DATABASE_URL``
names, and optionally the web app's Better Auth database.

The copy is deliberately conservative:

- Nothing may be running. A job holding an unexpired lease refuses the copy;
  stop the API and every worker first.
- Every target table must be empty, so a copy never merges into live data.
- Every store is first copied in a transaction that is rolled back (the dry
  run), so empty-table checks, type conversions and constraints are proven
  for all of them before any is committed. Each store then commits in its own
  transaction; if the connection fails between two commits, drop the target
  schemas and run it again.
- Rows are copied by column name in insertion order (SQLite ``rowid``), so
  tables that rely on insertion order (jobs, runs) keep it.
- Row counts are compared after the copy; any difference aborts.

Project repositories and delivery archives are files on the data volume and
are not touched. Manager-mode conversation sessions stay in SQLite.
"""
from __future__ import annotations

import sqlite3
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


# Better Auth's tables (its SQLite file holds nothing else Caveman needs).
AUTH_TABLES = frozenset({"user", "session", "account", "verification"})


class MigrationRefused(RuntimeError):
    """The copy would lose or merge data; nothing was written."""


@dataclass(frozen=True)
class StoreCopy:
    name: str
    source: Path
    schema: str
    tables: dict[str, int]


def _sqlite_tables(source: sqlite3.Connection) -> list[str]:
    # Creation order respects foreign keys: a referenced table is created first.
    rows = source.execute("SELECT name FROM sqlite_master WHERE type='table' "
                          "AND name NOT LIKE 'sqlite_%' ORDER BY rowid").fetchall()
    return [row[0] for row in rows]


def _sqlite_columns(source: sqlite3.Connection, table: str) -> set[str]:
    return {row[1] for row in source.execute(f'PRAGMA table_info("{table}")')}


def _target_columns(target, schema: str, table: str) -> dict[str, str]:
    rows = target.execute(
        "SELECT column_name, data_type, is_identity FROM information_schema.columns "
        "WHERE table_schema=%s AND table_name=%s ORDER BY ordinal_position", (schema, table)).fetchall()
    # Identity columns (the insertion-order `seq`) are generated by PostgreSQL.
    return {name: kind for name, kind, identity in rows if identity != "YES"}


def _convert(value, kind: str):
    """SQLite stores booleans as integers and timestamps as text or epoch numbers."""
    if value is None:
        return None
    if kind == "boolean":
        return bool(value)
    if kind.startswith("timestamp") or kind == "date":
        if isinstance(value, (int, float)):
            seconds = value / 1000 if value > 100_000_000_000 else value
            return datetime.fromtimestamp(seconds, tz=timezone.utc)
        parsed = datetime.fromisoformat(str(value).replace(" ", "T", 1))
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)
    return value


def copy_sqlite_to_postgres(source_path: Path, url: str, schema: str, *, name: str,
                            dry_run: bool = False, only: set[str] | None = None) -> StoreCopy:
    """Copy every table of one SQLite database into one PostgreSQL schema.

    The target tables must already exist (the stores create them on first open;
    Better Auth creates its own) and be empty. ``only`` limits the copy to the
    tables named in it, and every one of them must exist in SQLite.
    """
    import psycopg

    if not source_path.is_file():
        raise MigrationRefused(f"{name}: {source_path} does not exist")
    source = sqlite3.connect(f"file:{source_path}?mode=ro", uri=True)
    try:
        present_tables = _sqlite_tables(source)
        if only is not None:
            absent = sorted(only - set(present_tables))
            if absent:
                raise MigrationRefused(f"{name}: {source_path} lacks table(s) {', '.join(absent)}")
        tables = [table for table in present_tables if only is None or table in only]
        with psycopg.connect(url) as target:
            plan: list[tuple[str, list[str], dict[str, str]]] = []
            for table in tables:
                target_columns = _target_columns(target, schema, table)
                if not target_columns:
                    raise MigrationRefused(f"{name}: table {schema}.{table} does not exist in PostgreSQL")
                present = _sqlite_columns(source, table)
                missing = sorted(set(present) - set(target_columns))
                if missing:
                    raise MigrationRefused(f"{name}: {table} has columns PostgreSQL lacks: {', '.join(missing)}")
                count = target.execute(f'SELECT count(*) FROM "{schema}"."{table}"').fetchone()[0]
                if count:
                    raise MigrationRefused(f"{name}: {schema}.{table} already has {count} rows; "
                                           "the copy only goes into empty tables")
                # Columns SQLite lacks (added later in PostgreSQL) take their defaults.
                columns = [column for column in target_columns if column in present]
                plan.append((table, columns, target_columns))
            copied: dict[str, int] = {}
            with target.transaction():
                for table, columns, kinds in plan:
                    names = ", ".join(f'"{column}"' for column in columns)
                    rows = source.execute(f'SELECT {names} FROM "{table}" ORDER BY rowid').fetchall()
                    if rows:
                        insert = (f'INSERT INTO "{schema}"."{table}" ({names}) VALUES '
                                  f'({", ".join(["%s"] * len(columns))})')
                        with target.cursor() as cursor:
                            cursor.executemany(insert, [tuple(_convert(value, kinds[column])
                                                              for column, value in zip(columns, row))
                                                        for row in rows])
                    landed = target.execute(f'SELECT count(*) FROM "{schema}"."{table}"').fetchone()[0]
                    if landed != len(rows):
                        raise MigrationRefused(f"{name}: {table} copied {landed} of {len(rows)} rows")
                    copied[table] = landed
                if dry_run:
                    # Everything above ran for real, including constraints; undo it.
                    raise _DryRun(copied)
    except _DryRun as dry:
        return StoreCopy(name, source_path, schema, dry.copied)
    finally:
        source.close()
    return StoreCopy(name, source_path, schema, copied)


class _DryRun(Exception):
    def __init__(self, copied):
        super().__init__("dry run")
        self.copied = copied


def refuse_if_running(platform_db: Path) -> None:
    """Refuse while any job holds an unexpired lease: a worker is still writing."""
    if not platform_db.is_file():
        return
    connection = sqlite3.connect(f"file:{platform_db}?mode=ro", uri=True)
    try:
        leased = connection.execute("SELECT count(*) FROM jobs WHERE status='running' "
                                    "AND lease_expires > ?", (time.time(),)).fetchone()[0]
    finally:
        connection.close()
    if leased:
        raise MigrationRefused(f"{leased} job(s) are running; stop the API and all workers first")


def migrate_to_postgres(settings, *, auth_sqlite: Path | None = None, auth_url: str | None = None,
                        dry_run: bool = False) -> list[StoreCopy]:
    """Copy the operational and platform stores, then optionally Better Auth."""
    if not settings.database_url:
        raise MigrationRefused("Set CAVEMAN_DATABASE_URL to the PostgreSQL database to copy into")
    if (auth_sqlite is None) != (auth_url is None):
        raise MigrationRefused("Give both --auth-sqlite and --auth-url, or neither")
    if auth_url is not None and not auth_url.startswith(("postgres://", "postgresql://")):
        raise MigrationRefused("--auth-url must be a postgres:// URL")
    refuse_if_running(settings.platform_db)
    # Opening each SQLite store first brings it to the current schema version,
    # and opening the PostgreSQL stores creates their empty schemas.
    from walter.store import SQLiteStore, open_store

    from .platform_store import PlatformStore

    core = {"operations": settings.operations_db, "platform": settings.platform_db}
    found = [name for name, path in core.items() if path.is_file()]
    if len(found) == 1:
        missing = next(path for name, path in core.items() if name not in found)
        raise MigrationRefused(f"Found the {found[0]} store but not {missing}; "
                               "copy both core stores together or neither")
    sources = []
    if settings.operations_db.is_file():
        SQLiteStore(settings.operations_db).close()
        sources.append(("operations", settings.operations_db, f"{settings.database_schema}_ops"))
    if settings.platform_db.is_file():
        PlatformStore(settings.platform_db).close()
        sources.append(("platform", settings.platform_db, f"{settings.database_schema}_platform"))
    if not sources and auth_sqlite is None:
        raise MigrationRefused(f"No SQLite stores found in {settings.data_dir}")
    open_store(settings.database_url, schema=f"{settings.database_schema}_ops").close()
    PlatformStore(settings.database_url, schema=f"{settings.database_schema}_platform").close()

    def copy_all(rehearse: bool) -> list[StoreCopy]:
        results = [copy_sqlite_to_postgres(path, settings.database_url, schema, name=name, dry_run=rehearse)
                   for name, path, schema in sources]
        if auth_sqlite is not None:
            results.append(copy_sqlite_to_postgres(auth_sqlite, auth_url, "public", name="auth",
                                                   dry_run=rehearse, only=AUTH_TABLES))
        return results

    rehearsal = copy_all(True)
    return rehearsal if dry_run else copy_all(False)
